---

### PHP5 VARS
'php_ini': "/etc/php.ini"
'apache': "httpd"
'packages': [
                "php53",
                "php-pecl-apc",
                "php53-gd",
                "php53-mysql",
                "php53-xml",
                "php53-devel"
                ]
'session_save_path': "/var/lib/php/session"


# MYSQL VARS
'mysql': 'mysqld'
'mysqlpath': '/etc'
'socket': '/var/lib/mysql/mysql.sock'
'includedir': '/etc/sysconfig/mysqld-config'
'log_error': '/var/log/mysqld.log'

'mysqlpkg': 'mysql55'
'mysqlpkg_devel': 'mysql55-devel'


# PHPMYADMIN VARS
'phpmyadmin_name': 'phpMyAdmin'
'apache_conf_path': '/etc/httpd/conf.d'

